// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnS07wU7j99poUq3xb2XEqUQ-OaYoru_g',
    appId: '1:16939929676:web:043859b8c78b60da30e4e9',
    messagingSenderId: '16939929676',
    projectId: 'airplane-81378',
    authDomain: 'airplane-81378.firebaseapp.com',
    storageBucket: 'airplane-81378.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmlYXvx6sE9wu-LDlzwzFqmqdVze0lEF4',
    appId: '1:16939929676:android:efed7bee6039520f30e4e9',
    messagingSenderId: '16939929676',
    projectId: 'airplane-81378',
    storageBucket: 'airplane-81378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCbW2aBowiRUe1Ijm8b_48bRVmd_L1z14',
    appId: '1:16939929676:ios:febfa433557b7ef730e4e9',
    messagingSenderId: '16939929676',
    projectId: 'airplane-81378',
    storageBucket: 'airplane-81378.appspot.com',
    iosBundleId: 'com.example.airplane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCbW2aBowiRUe1Ijm8b_48bRVmd_L1z14',
    appId: '1:16939929676:ios:febfa433557b7ef730e4e9',
    messagingSenderId: '16939929676',
    projectId: 'airplane-81378',
    storageBucket: 'airplane-81378.appspot.com',
    iosBundleId: 'com.example.airplane',
  );
}
